load("https://www.alogh.com/Adventure.Land/code/working/main.js");
load("https://www.alogh.com/Adventure.Land/code/working/helperFunctions.js");
load("https://www.alogh.com/Adventure.Land/code/working/evadeTarget.js");
load("https://www.alogh.com/Adventure.Land/code/working/merchantSkills.js");
load("https://www.alogh.com/Adventure.Land/code/working/mageSkills.js");
load("https://www.alogh.com/Adventure.Land/code/working/priestSkills.js");
load("https://www.alogh.com/Adventure.Land/code/working/rangerSkills.js");
//load("https://www.alogh.com/Adventure.Land/code/working/followLead.js");
//load("https://www.alogh.com/Adventure.Land/code/working/farmAssist.js");