load("https://raw.githubusercontent.com/Nesousx/Adventure.Land/master/src/Main.js");
load("https://raw.githubusercontent.com/Nesousx/Adventure.Land/master/src/helperFunctions.js");
load("https://raw.githubusercontent.com/Nesousx/Adventure.Land/master/src/evadeTarget.js");
load("https://raw.githubusercontent.com/Nesousx/Adventure.Land/master/src/merchantSkills.js");
load("https://raw.githubusercontent.com/Nesousx/Adventure.Land/master/src/mageSkills.js");
load("https://raw.githubusercontent.com/Nesousx/Adventure.Land/master/src/priestSkills.js");
load("https://raw.githubusercontent.com/Nesousx/Adventure.Land/master/src/rangerSkills.js");
//load("https://raw.githubusercontent.com/Nesousx/Adventure.Land/master/src/followLead.js");
//load("https://raw.githubusercontent.com/Nesousx/Adventure.Land/master/src/farmAssist.js");