load("https://cdn.jsdelivr.net/gh/Nesousx/Adventure.Land/src/main.js");
load("https://cdn.jsdelivr.net/gh/Nesousx/Adventure.Land/src/helperFunctions.js");
load("https://cdn.jsdelivr.net/gh/Nesousx/Adventure.Land/src/evadeTarget.js");
load("https://cdn.jsdelivr.net/gh/Nesousx/Adventure.Land/src/merchantSkills.js");
load("https://cdn.jsdelivr.net/gh/Nesousx/Adventure.Land/src/mageSkills.js");
load("https://cdn.jsdelivr.net/gh/Nesousx/Adventure.Land/src/priestSkills.js");
load("https://cdn.jsdelivr.net/gh/Nesousx/Adventure.Land/src/rangerSkills.js");
//load("https://cdn.jsdelivr.net/gh/Nesousx/Adventure.Land/src/followLead.js");
//load("https://cdn.jsdelivr.net/gh/Nesousx/Adventure.Land/src/farmAssist.js");